### ISSUE TITLE
[FEAT] 테스트 결과 기본적인 UI 작업

### ISSUE THREAD

**Issue by CodyMan0** [dnd-side-project/dnd-10th-3-frontend#13]
## 요구사항
[TEST-3-01] 테스트 결과

## 상세 요구사항
- 테스트가 종료되면 결과를 보여줘야 합니다.
- 결과와 함께 ‘공유하기 버튼’과 ‘결과 저장하기 버튼’이 노출돼야 합니다.
- 다시 테스트 첫 화면으로 돌아갈 수 있는 ‘다시 테스트하기 버튼’이 노출돼야 합니다.
- “축의금 논쟁 종결짓기”와 같은 투표 커뮤니티로 이동할 수 있는 버튼이 있어야합니다.

## TODO
- [ ] 와이어 프레임 기반으로 기본적인 레아아웃 UI 구현
- [ ] 각 버튼 UI 구현
- [ ] 각 버튼 라우트 설정 

## 예상 소요 시간
2시간

## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Assignees(이슈 담당자)를 지정했습니다.
- [x] Labels, Milestone을 등록했습니다.
