### ISSUE TITLE
[FEAT] BottomSheet interface 작성 및 스토리 구현

### ISSUE THREAD

**Issue by CodyMan0** [dnd-side-project/dnd-10th-3-frontend#9]
## 요구사항

[System-1] BottomSheet 컴포넌트 

## TODO

- [ ] BottomSheet 라이브러리 선택
- [ ] BottomSheet 구현
- [ ] BottomSheet 스토리 구현

## 예상 소요 시간
1시간

## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Assignees(이슈 담당자)를 지정했습니다.
- [x] Labels, Milestone을 등록했습니다.
